apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  annotations:
    lsc-sde.nhs.uk/definitionVersion: "1.0.8"
spec:
  targetNamespace: jupyterhub
  releaseName: jupyterhub
  chart:
    spec:
      chart: jupyterhub
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
        namespace: jupyterhub
  interval: 5m0s
  timeout: 15m
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  valuesFrom:
  # Shared Config
  - kind: ConfigMap
    name: cull-config

  - kind: ConfigMap
    name: hub-custom-page-template

  - kind: ConfigMap
    name: hub-logo

  - kind: ConfigMap
    name: hub-config

  - kind: ConfigMap
    name: ingress-config

  - kind: ConfigMap
    name: proxy-config

  - kind: ConfigMap
    name: singleuser-config

  # Cluster Specific Configs
  - kind: ConfigMap
    name: environment-config

  - kind: ConfigMap
    name: user-config

  - kind: ConfigMap
    name: workspace-config

  - kind: Secret
    name: jupyter-credentials
    valuesKey: clientsecret
    targetPath: hub.config.AzureAdOAuthenticator.client_secret
