apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: jupyterhub
    component: hub
  name: hub-persistentvolumes
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["create", "list", "get"]