apiVersion: xlscsde.nhs.uk/v1
kind: ConfigMapTransform
metadata:
  name: jupyterhub-extra-files
spec:
  sourceRef:
    name: jupyterhub-extra-files
  targetConfigMap: jupyterhub-extra-files-encoded
  transforms:
  - key: jupyterhub_custom_config.py
    type: tobase64