apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jh-test:events-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: events-writer
subjects:
- kind: ServiceAccount
  name: hub
  namespace: jh-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jh-test:awms-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awms-test-admin
subjects:
- kind: ServiceAccount
  name: hub
  namespace: jh-test

  