apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${jupyter_hub_namespace}
resources:
- bindings.yaml
- role.yaml
- storageclass.yaml
- ingress.yaml
- workspaces.yaml
- datasources.yaml
- crates.yaml