# https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-file
# https://docs.microsoft.com/en-us/azure/aks/concepts-storage#storage-classes
# https://github.com/Azure/AKS/issues/929
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jupyter-default
provisioner: ${jupyter_storage_provisioner}
parameters:
  skuName: Standard_ZRS
  location: ${azure_location}
  storageAccount: ${azure_storage_account}
  storeAccountKey: "true"
  secretName: jupyter-storage
  secretNamespace: jupyterhub
  server: ${azure_storage_account}.privatelink.file.core.windows.net
  resourceGroup: ${azure_resource_group}
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=100
  - mfsymlinks # Enable support for Minshall+French symlinks 
  - cache=strict # https://linux.die.net/man/8/mount.cifs
  - actimeo=30 # reduce latency for metadata-heavy workload
  - nosharesock # reduce probability of reconnect race
allowVolumeExpansion: true
reclaimPolicy: Retain
