apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: jupyter-certificate-authority  
spec:
  sources:
  - useDefaultCAs: true

  - secret:
      name: "jupyter-certificate-authority-tls"
      key: "tls.crt"

  target:
    configMap:
      key: "root-certs.pem"
    additionalFormats:
      jks:
        key: "bundle.jks"
      pkcs12:
        key: "bundle.p12"

    namespaceSelector:
      matchLabels:
        lsc-sde.io/injectJupyterCertificates: "true"