apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: jupyterhub-certificate-authority${environment_dns_suffix}  
spec:
  sources:
  - useDefaultCAs: true

  - secret:
      name: "jupyter-certificate-authority-tls"
      key: "tls.crt"
  
  - secret:
      name: "keycloak-certificate-authority-tls"
      key: "tls.crt"

  target:
    configMap:
      key: "ca-certificates.crt"
    additionalFormats:
      jks:
        key: "jupyterhub.jks"
      pkcs12:
        key: "jupyterhub.p12"

    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: ${jupyter_hub_namespace}