apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: default-generic-workspace
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  displayName: Default Generic Workspace
  description: |
    Basic environment for testing with Python R and Julia.
  
  validity:
    availableFrom: "2022-01-01"
    expires: "2030-01-01"
  
  jupyterWorkspace:
    image: lscsde/datascience-notebook-default:0.1.19
    persistentVolumeClaim: 
      name: jupyter-default-generic-workspace
