prePuller:
  hook:
    enabled: true
hub:
  image:
    pullPolicy: Always
    name: lscsde/jupyterhub
    tag: 0.1.24
  config:
    GenericOAuthenticator:
      client_id: jupyter
      client_secret: jupyter
      keycloak_api_base_url: https://${environment_dns_prefix}keycloak${environment_dns_suffix}.${private_dnz_zone}/admin/realms/lsc-sde
      oauth_callback_url: ""
      authorize_url: https://${environment_dns_prefix}keycloak${environment_dns_suffix}.${private_dnz_zone}/realms/lsc-sde/protocol/openid-connect/auth
      token_url: https://${environment_dns_prefix}keycloak${environment_dns_suffix}.${private_dnz_zone}/realms/lsc-sde/protocol/openid-connect/token
      userdata_url: https://${environment_dns_prefix}keycloak${environment_dns_suffix}.${private_dnz_zone}/realms/lsc-sde/protocol/openid-connect/userinfo
      logout_redirect_url: https://${environment_dns_prefix}keycloak${environment_dns_suffix}.${private_dnz_zone}/realms/lsc-sde/protocol/openid-connect/logout
      login_service: keycloak
      scope: 
      - 'openid'
      - 'profile'
      - 'realm_groups'
      
      username_claim: workspace_id
      username_key: workspace_id
      userdata_params:
        state: state
        realm_groups: groups

      admin_groups:
      - jupyter-admins

      allowed_groups: 
      - jupyter-users

      claim_groups_key: groups

    AzureAdOAuthenticator:
      client_id: ${jupyterhub_client_id}
      oauth_callback_url: "https://${environment_dns_prefix}jupyter${environment_dns_suffix}.${private_dnz_zone}/hub/oauth_callback"
      tenant_id: ${azure_tenant_id}
      scope:
        - openid
        - name
        - profile
        - email
        - groups
        - roles
      username_claim: unique_name
      manage_groups: true
      allow_all: true
      allowed_groups:
      - "${jupyterhub_users_role}"
      - "${jupyterhub_admins_role}"
      user_groups_claim: groups
      admin_groups:
      - "${jupyterhub_admins_role}"
      allowed_users:
      - vishnu.chandrabalan@lthtr.nhs.uk
      - shaun.turner1@nhs.net
      admin_users:
      - vishnu.chandrabalan@lthtr.nhs.uk
      enable_auth_state: true
    JupyterHub:
      authenticator_class: generic-oauth
      admin_access: true
      template_paths:
        - "/usr/local/etc/jupyterhub/custom_templates"
      template_vars:
        announcement: |
          Preview only.
          Subject to rapid, breaking changes.
          Contact Vishnu.Chandrabalan@lthtr.nhs.uk with feedback/comments.
  # extraFiles: 
    # https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#hub-extrafiles
    # customSpawnPageTemplate:
    #   mountPath: /usr/local/etc/jupyterhub/custom_templates/spawn.html
      
    #customLogo:
    #  mountPath: /usr/local/share/jupyterhub/static/lander-logo.png
    # customPageTemplate:
    #   mountPath: /usr/local/etc/jupyterhub/custom_templates/page.html
   
    #customConfig:
    #  mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/jupyterhub_config_custom.py
    
  # https://discourse.jupyter.org/t/trouble-configuring-ingress-for-helm-chart/5050/3
  #baseUrl: /landerhub
  extraEnv:   
  - name: WORKSPACE_MANAGER
    value: lscsde
  livenessProbe:
    initialDelaySeconds: 5
fullnameOverride: "jupyterhub${environment_dns_suffix}"
nameOverride: "jupyterhub${environment_dns_suffix}"