prePuller:
  hook:
    enabled: true
hub:
  image:
    pullPolicy: Always
    name: lscsde/jh-93
    tag: 0.1.27-issues-93-launch-failure.5
  config:
    AzureAdOAuthenticator:
      client_id: ${jupyterhub_client_id}
      oauth_callback_url: "https://${environment_dns_prefix}jupyter${environment_dns_suffix}.${private_dnz_zone}/hub/oauth_callback"
      tenant_id: ${azure_tenant_id}
      scope:
        - openid
        - name
        - profile
        - email
        - groups
        - roles
      username_claim: unique_name
      manage_groups: true
      allow_all: true
      allowed_groups:
      - "${jupyterhub_users_role}"
      - "${jupyterhub_admins_role}"
      user_groups_claim: groups
      admin_groups:
      - "${jupyterhub_admins_role}"
      allowed_users:
      - vishnu.chandrabalan@lthtr.nhs.uk
      - shaun.turner1@nhs.net
      admin_users:
      - vishnu.chandrabalan@lthtr.nhs.uk
      enable_auth_state: true

    KubeSpawner:
      k8s_api_request_timeout: 10
      debug:
        enabled: true
        
    JupyterHub:
      authenticator_class: azuread
      admin_access: true
      template_paths:
        - "/usr/local/etc/jupyterhub/custom_templates"
      template_vars:
        announcement: |
          Preview only.
          Subject to rapid, breaking changes.
          Contact Vishnu.Chandrabalan@lthtr.nhs.uk with feedback/comments.
  # extraFiles: 
    # https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#hub-extrafiles
    # customSpawnPageTemplate:
    #   mountPath: /usr/local/etc/jupyterhub/custom_templates/spawn.html
      
    #customLogo:
    #  mountPath: /usr/local/share/jupyterhub/static/lander-logo.png
    # customPageTemplate:
    #   mountPath: /usr/local/etc/jupyterhub/custom_templates/page.html
   
    #customConfig:
    #  mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/jupyterhub_config_custom.py
    
  # https://discourse.jupyter.org/t/trouble-configuring-ingress-for-helm-chart/5050/3
  #baseUrl: /landerhub
  extraEnv:   
  - name: WORKSPACE_MANAGER
    value: lscsde
  - name: KS_START_TIMEOUT
    value: "120"
  livenessProbe:
    initialDelaySeconds: 5
fullnameOverride: "jupyterhub${environment_dns_suffix}"
nameOverride: "jupyterhub${environment_dns_suffix}"