prePuller:
  hook:
    enabled: true
hub:
  image:
    pullPolicy: Always
    name: lscsde/jupyterhub
    tag: 0.1.2
  config:
    AzureAdOAuthenticator:
      client_id: ${jupyterhub_client_id}
      oauth_callback_url: "https://${dns_prefix}jupyter.${private_dnz_zone}/hub/oauth_callback"
      tenant_id: ${azure_tenant_id}
      scope:
        - openid
        - name
        - profile
        - email
        - groups
        - upn
      username_claim: email
      #manage_groups: true
      #allowed_groups:
      #- admin
      #- user
      #user_groups_claim: groups
      admin_groups:
      - admin
      allowed_users:
      - vishnu.chandrabalan@lthtr.nhs.uk
      - shaun.turner1@nhs.net
      enable_auth_state: true
    JupyterHub:
      authenticator_class: azuread
      admin_access: true
      template_paths:
        - "/usr/local/etc/jupyterhub/custom_templates"
      template_vars:
        announcement: |
          Preview only.
          Subject to rapid, breaking changes.
          Contact Vishnu.Chandrabalan@lthtr.nhs.uk with feedback/comments.
  extraFiles:
    # https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#hub-extrafiles
    customSpawnPageTemplate:
      mountPath: /usr/local/etc/jupyterhub/custom_templates/spawn.html
      
    #customLogo:
    #  mountPath: /usr/local/share/jupyterhub/static/lander-logo.png
    customPageTemplate:
      mountPath: /usr/local/etc/jupyterhub/custom_templates/page.html
   
    #customConfig:
    #  mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/jupyterhub_config_custom.py
    
  # https://discourse.jupyter.org/t/trouble-configuring-ingress-for-helm-chart/5050/3
  #baseUrl: /landerhub
  extraEnv:   
  - name: WORKSPACE_MANAGER
    value: lscsde
  livenessProbe:
    initialDelaySeconds: 5
