apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${jupyter_namespace}
configMapGenerator:
  - name: cull-config
    files:
      - values.yaml=cull.yaml
  - name: hub-config
    files:
      - values.yaml=hub.yaml
  - name: hub-logo
    files:
      - values.yaml=hub-logo.yaml
  - name: ingress-config
    files:
      - values.yaml=ingress.yaml
  - name: proxy-config
    files:
      - values.yaml=proxy.yaml
  - name: singleuser-config
    files:
      - values.yaml=singleuser.yaml
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml
resources: []
  # - custom