singleuser:
  image:
    pullPolicy: IfNotPresent
  defaultUrl: "/lab"
  startTimeout: 900
  memory:
    limit: 4G
    guarantee: 256M
  cpu:
    limit: 1
    guarantee: 0.25
  storage:
    capacity: 10Gi
    homeMountPath: /home/jovyan/personal
    dynamic:
      storageAccessModes:
        - ReadWriteMany
  extraEnv:
    # See https://github.com/jupyter/notebook/issues/5058
    JUPYTER_RUNTIME_DIR: /tmp
