apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: arcnwc-chi-se419
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  displayName: ARCNWC-CHI-SE419
  description: |
    Socioeconomic Status and A&E Utilization across all levels of deprivation in the Lancashire Teaching Hospitals NHS Trust Catchment Area
  
  validity:
    availableFrom: "2024-02-22"
    expires: "2025-02-22"
  
  jupyterWorkspace:
    image: lscsde/datascience-notebook-default:0.1.0
    persistentVolumeClaim: 
      name: jupyter-arcnwc-chi-se419
