hub:
  config:
    GenericOAuthenticator:
      client_id: jupyter
      client_secret: KPGPTwAGW7QDWZnJEIRaUHt9em8FRfrH
      oauth_callback_url: http://jupyterhub.lsc-sde.local/hub/oauth_callback
      authorize_url: https://keycloak.lsc-sde.local/realms/lsc-sde/protocol/openid-connect/auth
      token_url: https://keycloak.lsc-sde.local/realms/lsc-sde/protocol/openid-connect/token
      userdata_url: https://keycloak.lsc-sde.local/realms/lsc-sde/protocol/openid-connect/userinfo
      logout_redirect_url: https://keycloak.lsc-sde.local/realms/lsc-sde/protocol/openid-connect/logout?redirect_uri=https://keycloak.lsc-sde.local/
      login_service: keycloak
      username_key: preferred_username
      userdata_params:
        state: state
    JupyterHub:
      authenticator_class: generic-oauth

  extraVolumes:
  - name: keycloak-certificates
    configMap:
      name: keycloak-certificate-authority
      defaultMode: 644
      items:
      - key: keycloak-certs.pem
        path: keycloak-certs.pem

  extraVolumeMounts:
  - name: keycloak-certificates
    mountPath: /etc/ssl/certs/keycloak-certs.pem
    subPath: keycloak-certs.pem
    readOnly: true
    
  lifecycle:
    postStart:
      exec:
        command:
        - sh
        - -c
        - sleep 10; update-ca-certificates

ingress:
  hosts: []
proxy:
  https:
    enabled: false
singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: latest

  storage:
    dynamic:
      storageClass: hostpath
