apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspaceBinding
metadata:
  name: advanced-generic-workspace-shaun-turner
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  workspace: advanced-generic-workspace
  username: "shaun.turner1@nhs.net"
  expires: "2030-01-01"