apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: arcnwc-chi-se421
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  displayName: ARCNWC-CHI-SE421
  description: |
    Utilisation of Health Care Record Linkage to Assess Potential for Intervention to prevent hospitalisation of infants with respiratory illness.
  
  validity:
    availableFrom: "2024-02-22"
    expires: "2025-02-22"
  
  jupyterWorkspace:
    image: lscsde/datascience-notebook-default:0.1.19
    persistentVolumeClaim: 
      name: jupyter-arcnwc-chi-se421
