apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${jupyter_hub_namespace}
configMapGenerator:
  - name: jupyterhub-extra-files
    files:
      #- jupyterhub_custom_config.py=jupyterhub_custom_config.py
      - page.html=page.html
      - spawn.html=spawn.html
generatorOptions:
  disableNameSuffixHash: true
resources:
  - jupyterhub-extra-files.yaml