apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sandbox-jupyter.privatelink.uksouth.azmk8s.io-tls
spec:
  isCA: true
  commonName: sandbox-jupyter.privatelink.uksouth.azmk8s.io
  secretName: tls-certificate
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: sde
    kind: ClusterIssuer
    group: cert-manager.io