hub:
  config:
    Authenticator:
      admin_users:
        - admin
      allowed_users:
        - user
    DummyAuthenticator:
      password: dummy-password
    JupyterHub:
      authenticator_class: dummy
    #AzureAdOAuthenticator:
    #  oauth_callback_url: https://sandbox-jupyter.privatelink.uksouth.azmk8s.io/landerhub/hub/oauth_callback
ingress:
  hosts:
    - sandbox-jupyter.privatelink.uksouth.azmk8s.io
proxy:
  https:
    hosts:
      - sandbox-jupyter.privatelink.uksouth.azmk8s.io
singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: latest

  storage:
    dynamic:
      storageClass: azurefile