apiVersion: batch/v1
kind: Job
metadata:
  name: jupyter-credentials-sync
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(100)"]
        volumeMounts:
        - name: secrets-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: jupyter-credentials-sync
      restartPolicy: Never
  backoffLimit: 4

