apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: neurosurgery-generic-workspace
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  displayName: Neurosurgery Generic Workspace
  description: |
    Workspace for Neurosurgery analytics  
  validity:
    availableFrom: "2024-03-13"
    expires: "2025-12-31"
  
  jupyterWorkspace:
    image: lscsde/datascience-notebook-default:0.1.0
    persistentVolumeClaim: 
      name: jupyter-neurosurgery-generic-workspace
