hub:
  config:
    GenericOAuthenticator:
      client_id: jupyter
      oauth_callback_url: https://${environment_dns_prefix}jupyter${environment_dns_suffix}.${private_dnz_zone}/hub/oauth_callback
      login_service: keycloak
      scope: 
      - 'openid'
      - 'profile'
      - 'realm_roles'
      - 'realm_groups'
      
      username_key: preferred_username
      userdata_params:
        state: state
        realm_roles: realm_roles
        realm_groups: realm_groups

      admin_groups:
      - jupyter-admins

      allowed_groups: 
      - jupyter-users

      claim_groups_key: realm_roles

    #JupyterHub:
    #  authenticator_class: generic-oauth

  extraVolumes:
  - name: jupyterhub-certificates
    configMap:
      name: jupyterhub-certificate-authority
      defaultMode: 0644

  extraVolumeMounts:
  - name: jupyterhub-certificates
    mountPath: /etc/ssl/certs
    readOnly: true

ingress:
  hosts: []
proxy:
  https:
    enabled: false
singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: latest

  storage:
    dynamic:
      storageClass: jupyter-default