hub:
  config:
    GenericOAuthenticator:
      client_id: jupyter
      client_secret: jupyter
      keycloak_api_base_url: https://${environment_dns_prefix}keycloak${environment_dns_suffix}.${private_dnz_zone}/admin/realms/lsc-sde
      oauth_callback_url: ""
      authorize_url: https://${environment_dns_prefix}keycloak${environment_dns_suffix}.${private_dnz_zone}/realms/lsc-sde/protocol/openid-connect/auth
      token_url: https://${environment_dns_prefix}keycloak${environment_dns_suffix}.${private_dnz_zone}/realms/lsc-sde/protocol/openid-connect/token
      userdata_url: https://${environment_dns_prefix}keycloak${environment_dns_suffix}.${private_dnz_zone}/realms/lsc-sde/protocol/openid-connect/userinfo
      logout_redirect_url: https://${environment_dns_prefix}keycloak${environment_dns_suffix}.${private_dnz_zone}/realms/lsc-sde/protocol/openid-connect/logout
      login_service: keycloak
      scope: 
      - 'openid'
      - 'profile'
      - 'realm_groups'
      
      username_claim: workspace_id
      username_key: workspace_id
      userdata_params:
        state: state
        realm_groups: groups

      admin_groups:
      - jupyter-admins

      allowed_groups: 
      - jupyter-users

      claim_groups_key: groups

  extraVolumes:
  - name: jupyterhub-certificates
    configMap:
      name: jupyterhub-certificate-authority${environment_dns_suffix}
      defaultMode: 0644

  extraVolumeMounts:
  - name: jupyterhub-certificates
    mountPath: /etc/ssl/certs
    readOnly: true

ingress:
  hosts: []
proxy:
  https:
    enabled: false
singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: latest

  storage:
    dynamic:
      storageClass: jupyter-default${environment_dns_suffix}