apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${jupyter_namespace}
resources:
  - secret.yaml
  - ingress.yaml
  - clusterrolebindings.yaml
  - storage
  - config
  - package
  - networkpolicy.yaml
configMapGenerator:
  - name: environment-config
    files:
      - values.yaml=configs.yaml
  - name: user-config
    files:
      - values.yaml=users.yaml
  - name: workspace-config
    files:
      - values.yaml=workspaces.yaml
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml
