apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: jupyter-storage
  annotations:
    xlscsde.nhs.uk/secretUsage: "Jupyter Storage Credentials"
spec:
  name: jupyter-storage
  type: Opaque
  secrets:
    - from: PrimaryStorageAccountKey
      to: azurestorageaccountkey
    - from: PrimaryStorageAccountName
      to: azurestorageaccountname
---
apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: jupyter-credentials
  annotations:
    xlscsde.nhs.uk/secretUsage: "Jupyter Client Credentials"
spec:
  name: jupyter-credentials
  secrets:
  - from: JupyterClientSecret
    to: clientsecret
---
apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: ${dns_prefix}jupyter.${private_dnz_zone}-tls
  annotations:
    xlscsde.nhs.uk/secretUsage: "Wildcard Certificate"
spec:
  name: ${dns_prefix}jupyter.${private_dnz_zone}-tls
  type: kubernetes.io/tls
  secrets:
  - from: WildcardCertificate
    to: tls.crt
  - from: WildcardCertificateKey
    to: tls.key
---
apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: jupyter-cookie
  annotations:
    xlscsde.nhs.uk/secretUsage: "Jupyter Cookie Secret"
spec:
  name: jupyter-cookie
  secrets:
  - from: JupyterCookieSecret
    to: jupyterhub_cookie_secret