apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: jupyter-credentials-sync
  annotations:
    jupyter.lsc-sde.io/secretUsage: "Jupyter Credentials"
spec:
  provider: azure
  secretObjects:
  - secretName: jupyter-storage
    type: Opaque
    data:
    - objectName: PrimaryStorageAccountKey
      key: azurestorageaccountkey
    - objectName: PrimaryStorageAccountName
      key: azurestorageaccountname
  - secretName: jupyter-credentials
    type: Opaque
    data:
    - objectName: JupyterClientSecret
      key: clientsecret

  - secretName: ${dns_prefix}jupyter.${private_dnz_zone}-tls
    type: kubernetes.io/tls
    data:
    - objectName: WildcardCertificate
      key: tls.crt
    - objectName: WildcardCertificateKey
      key: tls.key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${azure_client_id}
    keyvaultName: ${azure_keyvault_name}
    tenantId: "${azure_tenant_id}"
    objects: |
        array:
        - |
          objectName: PrimaryStorageAccountName
          objectType: secret
        - |
          objectName: PrimaryStorageAccountKey
          objectType: secret
        - |
          objectName: JupyterClientSecret
          objectType: secret
        - |
          objectName: WildcardCertificate
          objectType: secret
        - |
          objectName: WildcardCertificateKey
          objectType: secret