apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: jupyterhub
    component: hub
  name: hub-persistentvolumes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hub-persistentvolumes
subjects:
- kind: ServiceAccount
  name: jupyterhub${environment_dns_suffix}-hub