apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: jupyterhub-certificate-authority  
spec:
  sources:
  - useDefaultCAs: true

  - secret:
      name: "jupyter-certificate-authority-tls"
      key: "tls.crt"
  
  - secret:
      name: "keycloak-certificate-authority-tls"
      key: "tls.crt"

  - secret:
      name: nhs-certificates
      key: root-nwsis-ca.crt
      
  - secret:
      name: nhs-certificates
      key: sub-lth-ca

  target:
    configMap:
      key: "ca-certificates.crt"
    additionalFormats:
      jks:
        key: "jupyterhub.jks"
      pkcs12:
        key: "jupyterhub.p12"

    namespaceSelector:
      matchLabels:
        lsc-sde.io/injectJupyterCertificates: "true"