apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jupyterhub.lsc-sde.local-tls
spec:
  isCA: true
  commonName: jupyterhub.lsc-sde.local
  secretName: jupyterhub.lsc-sde.local-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: sde
    kind: ClusterIssuer
    group: cert-manager.io