hub:
  config:
    Authenticator:
      admin_users:
        - admin
      allowed_users:
        - user
    DummyAuthenticator:
      password: dummy-password
    JupyterHub:
      authenticator_class: dummy
ingress:
  hosts: []
proxy:
  https:
    enabled: false
singleuser:
  image:
    name: crlander.azurecr.io/vvcb/datascience-notebook
    tag: 0.1.0
