apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  values.yaml: |
    custom:
      users: &users
        "vishnu.chandrabalan@lthtr.nhs.uk":
          end_date: 2030-12-31
          workspaces: 
            # 00_ws_default:
            #   end_date: 2030-12-31
            10_ws_advanced:
              end_date: 2030-12-31
            colorectal_2ww_jupyter:
              end_date: 2030-12-31
            fft_jupyter:
              end_date: 2030-12-31
            vc-sd:
              end_date: 2025-12-31
            lth-dst:
              end_date: 2025-12-31
            gpu_workspace:
              end_date: 2025-12-31
            neuro_informatics_jupyter:
              end_date: 2023-11-30
            beamtree_adi_rstudio:
              end_date: 2023-05-23
            11_ws_codeserver:
              end_date: 2030-12-31
            nhsx_nlp:
              end_date: 2030-12-31
        "quinta.ashcroft@lthtr.nhs.uk":
          end_date: 2025-12-31
          workspaces:
            00_ws_default:
              end_date: 2025-12-31
            10_ws_advanced:
              end_date: 2025-12-31
            fft_jupyter:
              end_date: 2023-11-14
            lth-dst:
              end_date: 2025-12-31
            neuro_informatics_jupyter:
              end_date: 2023-11-30
            nhsx_nlp:
              end_date: 2030-12-31
        "timothy.howcroft@lthtr.nhs.uk":
          end_date: 2025-12-31
          workspaces:
            00_ws_default:
              end_date: 2025-12-31
            10_ws_advanced:
              end_date: 2025-12-31
            lth-dst:
              end_date: 2025-12-31
            nhsx_nlp:
              end_date: 2030-12-31
        "jo.knight@lthtr.nhs.uk":
          end_date: 2025-12-31
          workspaces:
            neuro_informatics_jupyter:
              end_date: 2023-11-30
            nhsx_nlp:
              end_date: 2030-12-31
        "stephen.dobson@lthtr.nhs.uk":
          end_date: 2025-12-31
          workspaces:
            00_ws_default:
              end_date: 2025-12-31
            10_ws_advanced:
              end_date: 2025-12-31
            vc-sd:
              end_date: 2025-12-31
            lth-dst:
              end_date: 2025-12-31
            10_ws_rstudo:
              end_date: 2025-12-31
            beamtree_adi_rstudio:
              end_date: 2023-05-23
            11_ws_codeserver:
              end_date: 2030-12-31
            nhsx_nlp:
              end_date: 2030-12-31
        "mubarak.patel@lthtr.nhs.uk":
          end_date: 2025-12-31
          workspaces:
            00_ws_default:
              end_date: 2025-12-31
            10_ws_advanced:
              end_date: 2025-12-31
        "mustafa.khanbhai@lthtr.nhs.uk":
          end_date: 2023-11-10
          workspaces:
            fft_jupyter:
              end_date: 2023-11-10
        "andrew.robinson@lthtr.nhs.uk":
          end_date: 2023-12-31
          workspaces:
            lth-dst:
              end_date: 2025-12-31
            10_ws_advanced:
              end_date: 2025-12-31
        "seyedparsa.hemmatihosseini@lthtr.nhs.uk":
          end_date: 2023-11-30
          workspaces:
            neuro_informatics_jupyter:
              end_date: 2023-11-30
            nhsx_nlp:
              end_date: 2030-12-31
        "levi.bassin@lthtr.nhs.uk":
          end_date: 2023-05-23
          workspaces:
            beamtree_adi_rstudio:
              end_date: 2023-05-23
        "david.bell@lthtr.nhs.uk":
          end_date: 2023-05-23
          workspaces:
            beamtree_adi_rstudio:
              end_date: 2023-05-23
        "aizaan.anwar@lthtr.nhs.uk":
          end_date: 2023-06-02
          workspaces:
            nhsx_nlp:
              end_date: 2023-06-02
        "paul.carroll@lthtr.nhs.uk":
          end_date: 2023-06-02
          workspaces:
            nhsx_nlp:
              end_date: 2023-06-02
        "jonathan.pearson@lthtr.nhs.uk":
          end_date: 2023-06-02
          workspaces:
            nhsx_nlp:
              end_date: 2023-06-02
