apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jupyter-certificate-authority${environment_dns_suffix}
spec:
  isCA: true
  commonName: jupyterhub local certificate
  secretName: jupyter-certificate-authority${environment_dns_suffix}-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: sde
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: jupyter-certificate-authority${environment_dns_suffix}
spec:
  ca:
    secretName: jupyter-certificate-authority${environment_dns_suffix}-tls
