apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
data:
  values.yaml: |
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/fssl-redirect: "true"
        # nginx.ingress.kubernetes.io/client_max_body_size: "0"
        nginx.ingress.kubernetes.io/proxy-body-size: 32m