apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jupyterhub
resources:
  - cull.yaml
  - hub.yaml
  - ingress.yaml
  - proxy.yaml
  - singleuser.yaml
configMapGenerator:
  - name: cull-config
    files:
      - values.yaml=cull.yaml
  - name: hub-config
    files:
      - values.yaml=hub.yaml
  - name: ingress-config
    files:
      - values.yaml=ingress.yaml
  - name: proxy-config
    files: 
      - values.yaml=proxy.yaml
  - name: singleuser-config
    files:
      - values.yaml=singleuser.yaml
configurations:
  - kustomizeconfig.yaml
