singleuser:
  image:
    pullPolicy: IfNotPresent
  defaultUrl: "/lab"
  startTimeout: 900
  memory:
    limit: 1G
    guarantee: 256M
  cpu:
    limit: 0.5
    guarantee: 0.25
  storage:
    capacity: 10Gi
    homeMountPath: /home/jovyan/personal
    dynamic:
      storageClass: azurefile
      storageAccessModes:
        - ReadWriteMany
  extraEnv:
    # See https://github.com/jupyter/notebook/issues/5058
    JUPYTER_RUNTIME_DIR: /tmp
