name: Create Release Branch from Main

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  semver:
    uses: lsc-sde/lsc-sde/.github/workflows/semver.yaml@main
    with:
      useConfigFile: true

  sandbox:
    uses: lsc-sde/lsc-sde/.github/workflows/flux.yaml@main
    needs: semver
    with:
      symver: ${{ needs.semver.outputs.GitVersion_SemVer }}
      environment: sandbox
      prefix: environments/sandbox
    secrets: inherit

  dev:
    uses: lsc-sde/lsc-sde/.github/workflows/flux.yaml@main
    needs: 
    - semver
    - sandbox
    with:
      symver: ${{ needs.semver.outputs.GitVersion_SemVer }}
      environment: dev
      prefix: environments/dev
    secrets: inherit

    
  production:
    uses: lsc-sde/lsc-sde/.github/workflows/flux.yaml@main
    needs:
    - semver
    - dev
    with:
      symver: ${{ needs.semver.outputs.GitVersion_SemVer }}
      environment: production
      prefix: release
    secrets: inherit
    